name: "deploy opus platform api to EC2"

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure at least two commits are available

      - name: "Check for changes"
        id: changes
        run: |
          # Ensure there is a previous commit
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            git diff --name-only HEAD^ HEAD > changed_files.txt
          else
            git diff --name-only HEAD > changed_files.txt
          fi

      - name: "Determine if build should be skipped"
        id: skip-check
        run: |
          SKIP_BUILD=true
          
          # Read changed files and check for patterns
          while IFS= read -r file; do
            if [[ ! "$file" =~ ^(database/|docs/|.*\.md)$ ]]; then
              SKIP_BUILD=false
              break
            fi
          done < changed_files.txt

          echo "SKIP_BUILD=$SKIP_BUILD" >> $GITHUB_ENV

      - name: "Output Build Status"
        run: |
          if [[ "$SKIP_BUILD" == "true" ]]; then
            echo "🚀 No relevant changes detected. Skipping build."
          else
            echo "✅ Relevant changes detected. A build would normally be triggered."
          fi
